# Introduction {#intro}

The Global Mosquito Alert Consortium's (GMAC's) best practices guides offer experiences gained from a variety of projects that use citizen science to better understand and combat disease-vector mosquitoes. The goal is to create a growing repository of information about how best to use and customize the GMAC’s citizen science toolkit for local implementation.

The present guide encompasses Pillar 4 of the GMAC toolkit: Vector Mosquito Monitoring via biodiversity specimen/DNA data sharing. This is a shared document to be used for developing an effective international citizen science network for vector mosquito monitoring, this part covering best practice in collecting mosquito specimens and DNA. Best practice for research data sharing has been handled differently by different fields, but an attempt to synthesis these was carried out by the Toronto International Data Release Workshop in 2009 (see: http://www.nature.com/nature/journal/v461/n7261/full/461168a.html). DNA data sharing has a particularly long history, and has lead the way in much of biological research. The principles for rapid release of genome-sequence data were first formulated the Bermuda (1996-1998) and [Fort Lauderdale (2003) meetings](https://www.genome.gov/10506537/), and remain the accepted policies recognised by the genomics community, journals and funders. Data producers were obliged to submit their data to one of the three [INSDC databases (EBI, NCBI or DDBJ)](http://www.insdc.org/) as soon as possible after the assembled sequence has met a set of quality evaluation criteria. In exchange for 'early release' of their data, the international sequencing centers retained the right to be the first to describe and analyze their complete datasets in peer-reviewed publications. Leading to the Toronto workshop, attendees endorsed the value of rapid pre-publication data release for large reference datasets in biology and medicine that have broad utility and agreed that pre-publication data release should go beyond genomics. This asks data producers to release their data, but they request a protected time period to allow them to be the first to publish the data set, this should be limited to global analyses of the data and ideally expire within one year.

Beyond making data open, best practice is now to follow the FAIR Guiding Principles for scientific data management and stewardship (see: https://www.nature.com/articles/sdata201618) which focuses on the interoperability and machine readability of datasets. To maximise the re-use of this citizen collected data the Global Mosquito Alert Consortium would ideally follow these overarching principles and practices. For more practical purposes there are more field specific guidelines and systems for dealing with collecting this type of insect biodiversity data that will be outlined in more detail below.


